[package]
name = "nll"
version = "0.1.0"
authors = ["Niko Matsakis <niko@alum.mit.edu>"]

[dependencies]
docopt = "0.6"
lalrpop-intern = "0.13.1"
nll-repr = { path = "../nll-repr" }
rustc-serialize = "0.3"
graph-algorithms = { path = "../graph-algorithms" }
lazy_static = "0.2.2"

[unstable]
rustc-serialize = "0.3"